### ISSUE TITLE
wire up RocksDB compaction TTL

### ISSUE THREAD

**Issue by jgraettinger** [LiveRamp/gazette#112]
We're now using a version of RocksDB which supports compaction TTLs, but have no way to turn this on from the Go side. It may require adding appropriate `cgo` extensions.

**Comment by rupertchen** [comment]
It appears that `rocksdb` has exposed all the C bindings that we will need. We need to update `gorocksdb` to expose `C.rocksdb_set_options` and passing `ttl` as the key.

Links into rocksdb source:
- https://github.com/facebook/rocksdb/blob/e1de88c8c74bbfbbfc80a8992bd6bb489bdfd194/include/rocksdb/c.h#L728
- https://github.com/facebook/rocksdb/blob/e1de88c8c74bbfbbfc80a8992bd6bb489bdfd194/include/rocksdb/advanced_options.h#L641
- https://github.com/facebook/rocksdb/blob/e1de88c8c74bbfbbfc80a8992bd6bb489bdfd194/include/rocksdb/c.h#L728
- https://github.com/facebook/rocksdb/blob/e1de88c8c74bbfbbfc80a8992bd6bb489bdfd194/options/options_helper.cc#L1893
- https://github.com/facebook/rocksdb/blob/5d4fddfa52768952e58abae5044174ad0ce30f7d/db/db_impl.cc#L714
- https://github.com/facebook/rocksdb/blob/5d4fddfa52768952e58abae5044174ad0ce30f7d/db/column_family.cc#L1142

**Comment by jgraettinger** [comment]
Excellent! Procrastination succeeds again.

**Comment by rupertchen** [comment]
My plan is to first make this change on top of our `update_rocksdb` fork, update gazette to use it, then cherry-pick that as a basis for a PR upstream. After that PR is merged, I'll revisit rebasing our fork.
