### ISSUE TITLE
Flaky test RecordedRocksDBSuite.TestPlayThenCancel

### ISSUE THREAD

**Issue by jskelcy** [LiveRamp/gazette#116]
Appears to flake on master

**Comment by jskelcy** [comment]
So far this has only been confirmed to flap on mac, I do not yet have a Linux development machine to test on.

The output from the failing test is as follows:

`----------------------------------------------------------------------
FAIL: recorder_rocksdb_test.go:169: RecordedRocksDBSuite.TestPlayThenCancel

recorder_rocksdb_test.go:180:
    // Blocks until |ctx| is cancelled.
    c.Check(errors.Cause(r.player.Play(deadlineCtx, FSMHints{Log: aRecoveryLog}, r.tmpdir, bk)),
        gc.Equals, context.DeadlineExceeded)
... obtained *status.statusError = &status.statusError{Code:4, Message:"context deadline exceeded", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0} ("rpc error: code = DeadlineExceeded desc = context deadline exceeded")
... expected context.deadlineExceededError = context.deadlineExceededError{} ("context deadline exceeded")
... Difference:
...     *status.statusError != context.deadlineExceededError


OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.13s)
FAIL
FAIL	github.com/LiveRamp/gazette/v2/pkg/recoverylog	1.113s`

**Comment by jgraettinger** [comment]
Thanks! Think I have an idea of what's happening here:

The test creates a context which is set to cancel after a deadline, and then starts a gRPC call which will block until that deadline is tripped. Usually that deadline is tripped while sitting in a blocking Read call, and `client.RetryReader` (and for that matter, so will `client.Reader`) will cause a `context.DeadlineExceeded` error to be returned, and the test passes.

Another possibility (say, if the test was running slow) is that the context cancellation could happen during the initial `client.Append` call which `recoverylog Player.Play` performs. That doesn't map a gRPC error to a `context.DeadlineExceeded` error, and instead is returning the raw gRPC error which basically says the same thing.

`errors.Cause` was my superficial attempt to make it work in all cases, that's in hindsight very broken.

We could:

1) Update this test to accept either a gRPC error with status code [DeadlineExceeded](https://godoc.org/google.golang.org/grpc/codes#Code), _or_ a `context.DeadlineExceeded`.

2) Update `client.Append` to return a context error over an RPC error, as [client.Reader](https://github.com/LiveRamp/gazette/blob/master/v2/pkg/client/reader.go#L80) does. This would work, though it does make me mildly uncomfortable (I don't love hiding errors). Maybe we can tighten this by mapping to a `context.DeadlineExceeded` (or similarly `context.Cancelled`) if and only if our context returns that error, *and* the gRPC error status is of the matching code? I think that would be pretty robust handling.
