### ISSUE TITLE
Gazette v2 gazconsumer equivalent 

### ISSUE THREAD

**Issue by jskelcy** [LiveRamp/gazette#175]
Gazette v1 included a binary called `gazconsumer` which exposed metrics that could be stitched together from both the broker and consumer processes, for example, consumer lag. 

There is currently no such tool in v2 and the functionality should be ported.

**Comment by jgraettinger** [comment]
I'd been thinking this should be part of `gazctl shards list` -- eg an extra flagged column added to the table / json view. There's a consumer `Stat` RPC which already includes / returns the journal read offsets of the shard, and brokers can be asked for journal write offsets, so it's a matter of issuing the RPCs and stitching the results.

**Comment by jskelcy** [comment]
This sounds perfect. This was just something I saw in v1 and noted there should be some analogue, but I think if we can avoid a new binary that is great.

**Comment by jgraettinger** [comment]
This looks fixed / can be closed? Thx
