### ISSUE TITLE
broker emitting noisy warnings with GCS backing store

### ISSUE THREAD

**Issue by rupertchen** [LiveRamp/gazette#194]
# Problem
There are a large number of warnings frequently being logged by brokers assigned to journals with stores on GCS. There is a warning from each journal every few minutes, but across all journals, this adds up to a lot of noise.

That said, this issue does not prevent the broker from performing its duty, so it is merely noisy, not broken.

# Proposals
The hypothesis is that the containing directory is included in the iteration across the objects since it matches the prefix in the query.

- Look for a way to exclude the directory from the results.
- Recognize the directory do not attempt to parse its name as a fragment file.
- Suppress the warning when the object is the directory.

# Example logs
```
Apr 2 11:59:45 hoping-pike-gazette-ffb6f6479-qclbr gazette warning {"bucket":"XXXX","err":"wrong Fragment format: YYYY","level":"warning","msg":"parsing fragment","name":"ZZZZ/YYYY/","time":"2019-04-02T15:59:45Z"}
```

**Comment by jgraettinger** [comment]
What's odd about this is that _something else_ is creating "directory"-like empty objects in the fragment store. gazette itself doesn't do this. Still, handling it is reasonable, as there are legitimate reasons for wanting these (eg, it's being mounted / interacted with as a GCS FUSE file-system, for example).

**Comment by jgraettinger** [comment]
Fixed.
